spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/test?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8&useSSL=false
server:
  port: 3000
mybatis-plus:
  global-config:
    db-config:
      #全局id自增策略
      id-type: auto